spring:
  jpa:
    flyway:
      enabled: true
      validate-on-migrate: true
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/${POSTGRES_GAMES_SERVICE_DB}
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
server:
  servlet:
    context-path: /games
  port: 8081




#spring:
#  jpa:
#    flyway:
#      enabled: true
#      validate-on-migrate: true
#    database: h2
#    properties.hibernate.temp.use_jdbc_metadata_defaults: false
#    hibernate:
#      ddl-auto: none
#    properties:
#  datasource:
#    database-platform: org.hibernate.dialect.H2Dialect
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2
#server:
#  servlet:
#    context-path: /games
#  port: 8081
