spring:
  cloud:
    config:
      enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
      routes:
        - id: games_service
          uri: lb://games-service
          predicates:
            - Path=/games/v1/catalogue/all
        - id: games_service
          uri: lb://games-service
          predicates:
            - Path=/games/v1/catalogue/specific/**
        - id: cart_service
          uri: lb://cart-service
          predicates:
            - Path=/cart/v1/update
        - id: cart_service
          uri: lb://cart-service
          predicates:
            - Path=/cart/v1/content
        - id: cart_service
          uri: lb://cart-service
          predicates:
            - Path=/cart/v1/orders
        - id: login_service
          uri: lb://login-service
          predicates:
            - Path=/login/v1/authorization
        - id: login_service
          uri: lb://login-service
          predicates:
            - Path=/login/v1/validate
