spring:
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # games-service routes
        - id: games-service
          uri: lb://games-service:8081/games
          predicates:
            - Path=/games/v1/catalogue/list/**"
        - id: games-service
          uri: lb://games-service:8081/games
          predicates:
            - Path=/games/v1/catalogue/**
        # cart-service routes
        - id: cart-service
          uri: lb://cart-service:8083/cart
          predicates:
            - Path=/cart/v1/update
        - id: cart-service
          uri: lb://cart-service:8083/cart
          predicates:
            - Path=/cart/v1/content
        - id: cart-service
          uri: lb://cart-service:8083/cart
          predicates:
            - Path=/cart/v1/purchase/**
        # login-service routes
        - id: login-service
          uri: lb://login-service:8082/login
          predicates:
            - Path=/login/v1/authorization
        - id: login-service
          uri: lb://login-service:8082/login
          predicates:
            - Path=/login/v1/registration
        # orders-service routes
        - id: orders-service
          uri: lb://orders-service:8084/orders
          predicates:
            - Path=/orders/v1/purchases/**
