spring:
  cloud:
    config:
      enabled: true
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: games_service
          uri: http://localhost:8081/games
          predicates:
            - Path=/games/v1/catalogue/list/**"
        - id: games_service
          uri: http://localhost:8081/games
          predicates:
            - Path=/games/v1/catalogue/**
              
              
              
        - id: cart_service
          uri: http://localhost:8083/cart
          predicates:
            - Path=/cart/v1/update
        - id: cart_service
          uri: http://localhost:8083/cart
          predicates:
            - Path=/cart/v1/getContent
        - id: cart_service
          uri: http://localhost:8083/cart
          predicates:
            - Path=/cart/v1/orders
              
              
              
        - id: login_service
          uri: http://localhost:8082/login
          predicates:
            - Path=/login/v1/authorization

